### ISSUE TITLE
Bio, photo and social  - Lucas

### ISSUE THREAD

**Issue by hiyama341** [OpenCloning/OpenCloning_landing_page#1]
Bio Lucas 

Hi, I'm Lucas.
I'm a PhD researcher in synthetic biology at DTU Bioengineering. After doing my BSc at the University of Copenhagen and my MSc from the Technical University of Denmark, with exchange semesters at the National University of Singapore (NUS) and École Polytechnique Fédérale de Lausanne (EPFL) in Switzerland, I dove into projects like [teemi](https://github.com/hiyama341/teemi), an open-source literate programming framework for bioengineering. Currently, I'm developing web apps and high-throughput genetic engineering platforms for Streptomyces and Aspergillus. I'm passionate about combining biology and programming to accelerate synthetic biology and automate workflows. Reach out if you are interested in collabs. 

Photo: 
https://media.licdn.com/dms/image/v2/C4D03AQH1iAa_NnAFJw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1611761701213?e=1736380800&v=beta&t=maUe_0tTtK6-sIbcOLpsczWY_XBpXofExMVVFJCSrcM

Linkedin: https://www.linkedin.com/in/lucas-levassor/
Orchid: https://orcid.org/0000-0002-3261-9911
twitter: https://x.com/Colonellucas27

**Comment by manulera** [comment]
Updated!
