### ISSUE TITLE
Bio and links

### ISSUE THREAD

**Issue by dgruano** [OpenCloning/OpenCloning_landing_page#2]
Daniel García-Ruano studied experimental evolution in fission yeast during his PhD, gaining interest in computational approaches and reproducibility in science. He started collaborating with ShareYourCloning as a testing user to later dive in the code and implement new use cases. Currently, he is a non-tenured associate professor in Cell Biology at the University of Bordeaux, with a research intereset in machine learning for transcript classification.

https://x.com/soybiotec/
https://www.linkedin.com/in/dgruano/
https://orcid.org/0000-0002-5033-8013/

![fotolab_720](https://github.com/user-attachments/assets/3772ac89-d5e2-4079-aa3c-b71b7dd23c93)

**Comment by manulera** [comment]
Updated!
